colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

replyByEmail = false

mainSections = ["geodev", "osgeo-konferenca", "svizec"]

disableImageOptimization = false
disableTextInHeader = false

fingerprintAlgorithm = "sha256"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/geodev/"
  cardView = true

[article]
  showDate = true
  showAuthor = false
  showHero = false
  showBreadcrumbs = true
  showHeadingAnchors = true
  showPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = false
  groupByYear = true
  cardView = true
